Application.ensure_all_started(:inets)
ExUnit.start(capture_log: true)

Mox.defmock(Engine.NetworkCheck.Mock, for: Engine.NetworkCheck)
Mox.defmock(PaEss.Updater.Mock, for: PaEss.Updater)
Mox.defmock(Engine.Config.Mock, for: Engine.Config)
Mox.defmock(Engine.Alerts.Mock, for: Engine.Alerts)
Mox.defmock(Engine.Predictions.Mock, for: Engine.Predictions)
Mox.defmock(Engine.ScheduledHeadways.Mock, for: Engine.ScheduledHeadways)
Mox.defmock(Engine.Locations.Mock, for: Engine.Locations)
Mox.defmock(Engine.LastTrip.Mock, for: Engine.LastTrip)
Mox.defmock(Engine.ChelseaBridge.Mock, for: Engine.ChelseaBridge)
Mox.defmock(Engine.Routes.Mock, for: Engine.Routes)
Mox.defmock(Engine.BusPredictions.Mock, for: Engine.BusPredictions)
Mox.defmock(Engine.BusStops.Mock, for: Engine.BusStops)
