  @headsign_abbreviation_mappings [
    {"Ruggles", ["Ruggles"]},
    {"Downtown", ["Downtwn", "Downtown"]},
    {"South Station", ["So Sta", "SouthSta", "South Sta"]},
    {"Harvard", ["Harvard"]},
    {"Ashmont", ["Ashmont"]},
    {"Harbor Point", ["HarbrPt", "HarborPt", "Harbor Pt"]},
    {"Kenmore", ["Kenmore"]},
    {"Broadway", ["Broadwy", "Broadway"]},
    {"Roslindale", ["Roslndl", "Roslndal", "Roslindal"]},
    {"Millennium Park", ["MillnPk", "MillenPk", "Millen Pk"]},
    {"Heath St", ["HeathSt", "Heath St"]},
    {"Kane Square", ["Kane Sq"]},
    {"St Peter's Square", ["StPeter", "StPeteSq", "StPeterSq"]},
    {"Fields Corner", ["FldsCor", "Flds Cor", "FieldsCor"]},
    {"Mattapan", ["Mattapn", "Mattapan"]},
    {"Central", ["Central"]},
    {"Jackson", ["Jackson"]},
    {"Centre St & Eliot St", ["CentrSt", "CentreSt", "Centre St"]},
    {"JFK", ["JFK UMA", "JFKUMass", "JFK/UMass"]},
    {"Forest Hills", ["FrstHls", "Frst Hls", "ForestHls"]},
    {"Franklin Park", ["FrklnPk", "FrnklnPk", "FranklnPk"]},
    {"Arlington Center", ["Arlngtn", "Arlingtn", "Arlington"]},
    {"Clarendon Hill", ["Clarndn", "Clarendn", "Clarendon"]},
    {"Watertown", ["Watertn", "Watertwn", "Watertown"]},
    {"Huron Ave", ["HuronAv", "Huron Av", "Huron Ave"]},
    {"Aberdeen Ave", ["Abrdeen", "Aberdeen", "AbrdeenAv"]},
    {"Waverley", ["Waverly", "Waverley"]},
    {"Belmont", ["Belmont"]},
    {"Arlington Heights", ["Arlngtn", "Arlingtn", "Arlington"]},
    {"North Cambridge", ["N Camb", "NorthCamb"]},
    {"Arlmont", ["Arlmont"]},
    {"Sullivan", ["Sullivn", "Sullivan"]},
    {"Medford", ["Medford"]},
    {"Wakefield Ave", ["WkfldAv", "WakfldAv", "WakefldAv"]},
    {"Quincy Center", ["Quincy", "QuincyCtr"]},
    {"River St & Milton St", ["MiltnSt", "MiltonSt", "Milton St"]},
    {"Quincy Ctr", ["Quincy", "QuincyCtr"]},
    {"Dudley", ["Dudley"]},
    {"Assembly", ["Asembly", "Assembly"]},
    {"Wellington", ["Welngtn", "Welingtn", "Welington"]},
    {"Back Bay", ["BackBay", "Back Bay"]},
    {"Georgetowne", ["Georgtn", "Georgtwn", "Georgtwne"]},
    {"Cleary Sq", ["Clry Sq", "ClearySq", "Cleary Sq"]},
    {"Reservoir", ["Resrvor", "Resrvoir", "Reservoir"]},
    {"Wren St", ["Wren St"]},
    {"Dedham Line", ["DdmLine", "DedmLine", "DedhmLine"]},
    {"Dedham Sq", ["DedhmSq", "DedhamSq", "Dedham Sq"]},
    {"Legacy Place", ["Legacy", "LegacyPl", "Legacy Pl"]},
    {"Walpole Center", ["WlplCtr", "WalplCtr", "Walpl Ctr"]},
    {"East Walpole", ["E Walpl", "E Walpol", "E Walople"]},
    {"Stimson St", ["StmsnSt", "StimsnSt", "Stimsn St"]},
    {"Dedham Mall", ["DdmMall", "DedmMall", "DedhmMall"]},
    {"Charles River Loop", ["CharlRv", "CharlsRv", "CharlsRiv"]},
    {"Rivermoor", ["Rivmoor", "Rivrmoor", "Rivermoor"]},
    {"VA Hospital", ["VA Hosp", "V A Hosp"]},
    {"Baker & Vermont St", ["BakerSt", "Baker St"]},
    {"Columbian Sq", ["Clmbian", "Colmbian", "Columbian"]},
    {"Montello", ["Mntello", "Montello"]},
    {"South Shore Plaza", ["SoShPlz", "SoShPlza", "SoShPlaza"]},
    {"LaGrange St & Corey St", ["LaGrang", "LaGrange"]},
    {"LaGrange & Corey", ["LaGrang", "LaGrange"]},
    {"Townsend & Humboldt", ["Twnsend", "Townsend", "TownsndSt"]},
    {"Union Sq", ["UnionSq", "Union Sq"]},
    {"Logan Airport", ["Airport"]},
    {"Boston Medical Center", ["Bos Med"]},
    {"Brighton Center", ["Brightn", "Brighton"]},
    {"Louis Pasteur Ave", ["AvPastr", "Av Pastr", "AvPasteur"]},
    {"Ave Louis Pasteur", ["AvPastr", "Av Pastr", "AvPasteur"]},
    {"Avenue Louis Pasteur", ["AvPastr", "Av Pastr", "AvPasteur"]},
    {"Longwood Ave", ["AvPastr", "Av Pastr", "AvPasteur"]},
    {"Nubian", ["Nubian", "NubianSta"]},
    {"Adams & Gallivan", ["Gallivn", "Gallivan"]},
    {"Waltham", ["Waltham"]},
    {"Haymarket", ["Haymrkt", "Haymarkt", "Haymarket"]},
    {"Silver Line Way", ["Slvr Ln Way"]},
    {"Drydock", ["Drydock"]}
  ]
  @headsign_take_mappings [
    {"Ruggles", "4086"},
    {"Downtown", "563"},
    {"South Station", "4089"},
    {"Harvard", "4003"},
    {"Ashmont", "4016"},
    {"Harbor Point", "564"},
    {"Kenmore", "4201"},
    {"Broadway", "4010"},
    {"Roslindale", "560"},
    {"Millennium Park", "676"},
    {"Heath St", "4204"},
    {"Kane Square", "558"},
    {"St Peter's Square", "572"},
    {"Fields Corner", "4014"},
    {"Mattapan", "4100"},
    {"Central", "4004"},
    {"Jackson", "4040"},
    {"Centre St & Eliot St", "557"},
    {"JFK", "4012"},
    {"Forest Hills", "4043"},
    {"Franklin Park", "559"},
    {"Arlington Center", "613"},
    {"Clarendon Hill", "605"},
    {"Watertown", "606"},
    {"Huron Ave", "607"},
    {"Aberdeen Ave", "804"},
    {"Waverley", "608"},
    {"Belmont", "609"},
    {"Arlington Heights", "610"},
    {"North Cambridge", "611"},
    {"Arlmont", "612"},
    {"Sullivan", "4025"},
    {"Medford", "614"},
    {"Wakefield Ave", "621"},
    {"Quincy Center", "620"},
    {"River St & Milton St", "619"},
    {"Quincy Ctr", "620"},
    {"Dudley", "632"},
    {"Assembly", "4209"},
    {"Wellington", "4024"},
    {"Back Bay", "4036"},
    {"Georgetowne", "674"},
    {"Cleary Sq", "670"},
    {"Reservoir", "4076"},
    {"Wren St", "698"},
    {"Dedham Line", "671"},
    {"Dedham Sq", "847"},
    {"Legacy Place", "848"},
    {"Walpole Center", "697"},
    {"East Walpole", "673"},
    {"Stimson St", "693"},
    {"Dedham Mall", "672"},
    {"Charles River Loop", "669"},
    {"Rivermoor", "677"},
    {"VA Hospital", "696"},
    {"Baker & Vermont St", "668"},
    {"Columbian Sq", "805"},
    {"Montello", "806"},
    {"South Shore Plaza", "808"},
    {"LaGrange St & Corey St", "675"},
    {"LaGrange & Corey", "675"},
    {"Townsend & Humboldt", "694"},
    {"Union Sq", "695"},
    {"Logan Airport", "562"},
    {"Boston Medical Center", "568"},
    {"Brighton Center", "566"},
    {"Louis Pasteur Ave", "567"},
    {"Ave Louis Pasteur", "567"},
    {"Avenue Louis Pasteur", "567"},
    {"Longwood Ave", "567"},
    {"Nubian", "812"},
    {"Adams & Gallivan", "569"},
    {"Waltham", "561"},
    {"Haymarket", "4028"},
    {"Silver Line Way", "570"},
    {"Drydock", "571"}
  ]
  @route_take_lookup %{
    "SL5" => "587",
    "SL4" => "586",
    "1" => "573",
    "8" => "574",
    "14" => "575",
    "15" => "576",
    "19" => "577",
    "23" => "578",
    "24" => "622",
    "27" => "623",
    "2427" => "629",
    "28" => "579",
    "29" => "624",
    "30" => "625",
    "31" => "626",
    "33" => "627",
    "34" => "678",
    "34E" => "679",
    "35" => "680",
    "36" => "681",
    "37" => "682",
    "38" => "683",
    "39" => "684",
    "40" => "685",
    "41" => "580",
    "42" => "581",
    "44" => "582",
    "45" => "583",
    "47" => "584",
    "50" => "686",
    "51" => "687",
    "66" => "585",
    "69" => "590",
    "71" => "591",
    "72" => "592",
    "73" => "594",
    "74" => "595",
    "75" => "596",
    "77" => "597",
    "77A" => "598",
    "78" => "599",
    "80" => "600",
    "86" => "601",
    "87" => "602",
    "88" => "603",
    "89" => "688",
    "90" => "689",
    "94" => "690",
    "96" => "604",
    "170" => "588",
    "171" => "589",
    "226" => "809",
    "230" => "810",
    "236" => "811",
    "245" => "628"
  }