name: Asana integration
on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  asana:
    uses: mbta/workflows/.github/workflows/asana.yml@v4
    with:
      attach-pr: true
      trigger-phrase: "\\*\\*Asana Ticket:\\*\\*"
    secrets:
      asana-token: ${{ secrets.ASANA_SECRET_FOR_INSURIFY_ACTION_TEST }}
      github-secret: ${{ secrets.ASANA_GITHUB_INTEGRATION_SECRET_TEST }}
