name: Deploy to Dev-green

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: windows-2019
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: mbta/actions/build-push-ecr@v2
        id: build-push
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          docker-repo: ${{ secrets.DOCKER_REPO }}
  deploy:
    name: Deploy
    needs: build
    uses: mbta/workflows/.github/workflows/deploy-on-prem.yml@v2
    with:
      app-name: realtime-signs
      environment: dev-green
      on-prem-cluster: hsctd-dev-managers
      splunk-index: realtime-signs-dev-green
      task-cpu: .5
      task-memory: 2048M
      task-port: 8080
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
      docker-repo: ${{ secrets.DOCKER_REPO }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
