name: Build container

on:
  push:
    branches-ignore:
      - master

permissions: {}

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    name: linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: docker build .
